external_data_config:
  external_data_csv: data/external/BankAnalysis.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: ['deposit','duration(in minutes)', 'ordinal_month', 'day', 'age', 'balance','ordinal_poutcome', 'ordinal_job', 'campaign', 'ordinal_contact','housing']
  train_test_split_ratio: 0.2
  target: deposit 
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/ds_train.csv
  test_data_csv:  data/processed/ds_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: rf
  registered_model_name: rf_model
  remote_server_uri: http://127.0.0.1:5000
 
random_forest: 
  max_depth: 8
  n_estimators: 20

model_dir: models/model.joblib

#model_webapp_dir: webapp/model_webapp_dir/model.joblib
#api_webapp_url: https://flask-joenvihe-api.herokuapp.com/prediction/{}

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html

